name: jdmcarspain.com
favicon: null
layout_spectrum: 0.7549668741412461
typography_spectrum: 0.18313243123702705
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121212'
    - '#6c6c6c'
    - '#9e9e9e'
    - '#be2b3a'
    - '#febec2'
  brandStrength: 0.375
  lightness: 0.8125
  saturation: 0.625
  rhythmicContrast: 0.23874206049367785
purpose: []
